# Site settings
title: Stylish Portfolio
email: bjhenderson@mac.com
description: > # this means to ignore newlines until "baseurl:"
  Moving in or to Maryland? John Henderson is a local cheseapake blooded native who is passionate about helping
  others throughout their realty transitions. Whether you're family is going and you need a bigger home, you 
  hope to downsize, or you've relocated to our amazing area for work. John is here to work with you and support 
  you in your real estate transitions. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# User setting
owner: John Henderson
email: name@example.com
facebook_username: example
twitter_username: example
github_username: example
address:
  - line: 3481 Melrose Hill St
  - line: "Los Angeles, CA 90029"
  # Feel free to add more lines here 
telephone: (123) 456-7890
copyright: Your Site

# API settings
google_api_key: AIzaSyA8H0jVz_6Hc273rqNYKQ6AAiBvQfVKmYQ

# Build settings
markdown: kramdown
